### ISSUE TITLE
Can't get this working

### ISSUE THREAD

**Issue by nk9** [rimvaliulin/isorted#1]
The README says I can "just find `isort` in PackageControl," but there seem to be two problems with this:

1. Isn't this package called "iSorted"?
2. The package `isort` already exists and points to [this other package](https://github.com/asfaltboy/sublime-text-isort-plugin).

I'd like to use your package, since the current one [seems to have been abandoned](https://github.com/asfaltboy/sublime-text-isort-plugin/pull/2). But I can't find it on PackageControl, and when I clone it into the [Packages folder](https://stackoverflow.com/a/49967132) and restart Sublime, I still don't see it in Sublime Text > Preferences > Packages.

I'm using Sublime 4, build 4126. Any idea what might be wrong? And can you confirm for me that your package will properly load the isort configuration in a project's `./pyproject.toml` file? (That's the reason I can't use the other package, it's ignoring the config files for some reason.)

Thanks!

**Comment by rimvaliulin** [comment]
I didn't add the package to PackageControl yet. There's some minor issues with new version Sublime Text which I can't figure out. As soon I solve this I'll add to PackageControl.
