### ISSUE TITLE
How is this different from sublime-text-isort-plugin?

### ISSUE THREAD

**Issue by reagle** [rimvaliulin/isorted#2]
For folks looking for a plugin, perhaps you could state in the README how yours is different from https://github.com/asfaltboy/sublime-text-isort-plugin .

**Comment by rimvaliulin** [comment]
It uses external isort package, [sublime-text-isort-plugin](https://github.com/asfaltboy/sublime-text-isort-plugin) uses hardcoded version which pretty old now.

**Comment by reagle** [comment]
Perhaps you could say as much on the README?
